# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FormValidator-Simple-Plugin-CDBI-Unique
version:      0.03
version_from: lib/FormValidator/Simple/Plugin/CDBI/Unique.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    FormValidator::Simple:         0.11
    SQL::Abstract:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
